--
-- PostgreSQL database dump
--

-- Dumped from database version 16.1
-- Dumped by pg_dump version 16.1

-- Started on 2023-12-16 14:21:54

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 4831 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 225 (class 1259 OID 16431)
-- Name: tb_cart_temp; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_cart_temp (
    id integer NOT NULL,
    id_users integer NOT NULL,
    id_products integer NOT NULL,
    jumlah integer NOT NULL
);


ALTER TABLE public.tb_cart_temp OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16436)
-- Name: tb_cart_temp_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tb_cart_temp ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_cart_temp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 9999
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16421)
-- Name: tb_detail_transaksi; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_detail_transaksi (
    id integer NOT NULL,
    id_transaksi integer NOT NULL,
    total_product integer NOT NULL,
    harga_product integer NOT NULL,
    nama_product character varying(255) NOT NULL
);


ALTER TABLE public.tb_detail_transaksi OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16430)
-- Name: tb_detail_transaksi_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tb_detail_transaksi ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_detail_transaksi_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 9999
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 16411)
-- Name: tb_inventory_products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_inventory_products (
    id integer NOT NULL,
    id_products integer NOT NULL,
    jumlah_masuk integer NOT NULL,
    jumlah_keluar integer NOT NULL,
    created_at character varying(50) NOT NULL
);


ALTER TABLE public.tb_inventory_products OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16429)
-- Name: tb_inventory_products_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tb_inventory_products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_inventory_products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 9999
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 16404)
-- Name: tb_products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_products (
    id integer NOT NULL,
    nama_product character varying(255) NOT NULL,
    harga integer NOT NULL,
    photo character varying(255) NOT NULL,
    jumlah integer NOT NULL
);


ALTER TABLE public.tb_products OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16428)
-- Name: tb_products_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tb_products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 9999
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16416)
-- Name: tb_transaksi; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_transaksi (
    id integer NOT NULL,
    invoice character varying(50) NOT NULL,
    id_users integer NOT NULL,
    created_at character varying(50) NOT NULL
);


ALTER TABLE public.tb_transaksi OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16427)
-- Name: tb_transaksi_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tb_transaksi ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_transaksi_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 9999
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 16399)
-- Name: tb_users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_users (
    id integer NOT NULL,
    email character varying(100) NOT NULL,
    password character varying(100) NOT NULL,
    nama character varying(255) NOT NULL,
    no_telp character varying(15) NOT NULL,
    role_id integer NOT NULL
);


ALTER TABLE public.tb_users OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16426)
-- Name: tb_users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tb_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 9999
    CACHE 1
);


--
-- TOC entry 4824 (class 0 OID 16431)
-- Dependencies: 225
-- Data for Name: tb_cart_temp; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4818 (class 0 OID 16421)
-- Dependencies: 219
-- Data for Name: tb_detail_transaksi; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.tb_detail_transaksi (id, id_transaksi, total_product, harga_product, nama_product) VALUES (1, 1, 100, 5000, 'Sari Roti - Coklat');
INSERT INTO public.tb_detail_transaksi (id, id_transaksi, total_product, harga_product, nama_product) VALUES (2, 2, 10, 15000, 'sepatu');
INSERT INTO public.tb_detail_transaksi (id, id_transaksi, total_product, harga_product, nama_product) VALUES (3, 3, 2, 15000, 'sepatu');
INSERT INTO public.tb_detail_transaksi (id, id_transaksi, total_product, harga_product, nama_product) VALUES (4, 3, 5, 7000, 'Sari Roti - Coklat');
INSERT INTO public.tb_detail_transaksi (id, id_transaksi, total_product, harga_product, nama_product) VALUES (5, 4, 2, 10000, 'jaket');
INSERT INTO public.tb_detail_transaksi (id, id_transaksi, total_product, harga_product, nama_product) VALUES (6, 5, 250, 10000, 'Biscuit');
INSERT INTO public.tb_detail_transaksi (id, id_transaksi, total_product, harga_product, nama_product) VALUES (7, 6, 300, 30000, 'parfum');
INSERT INTO public.tb_detail_transaksi (id, id_transaksi, total_product, harga_product, nama_product) VALUES (8, 7, 300, 50000, 'tas sekolah');
INSERT INTO public.tb_detail_transaksi (id, id_transaksi, total_product, harga_product, nama_product) VALUES (9, 8, 100, 15000, 'sepatu');
INSERT INTO public.tb_detail_transaksi (id, id_transaksi, total_product, harga_product, nama_product) VALUES (10, 9, 50, 10000, 'jaket');
INSERT INTO public.tb_detail_transaksi (id, id_transaksi, total_product, harga_product, nama_product) VALUES (11, 9, 50, 50000, 'tas sekolah');


--
-- TOC entry 4816 (class 0 OID 16411)
-- Dependencies: 217
-- Data for Name: tb_inventory_products; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.tb_inventory_products (id, id_products, jumlah_masuk, jumlah_keluar, created_at) VALUES (11, 7, 700, 300, '13 December 2023, 09:51:57');
INSERT INTO public.tb_inventory_products (id, id_products, jumlah_masuk, jumlah_keluar, created_at) VALUES (12, 3, 800, 600, '13 December 2023, 09:51:57');
INSERT INTO public.tb_inventory_products (id, id_products, jumlah_masuk, jumlah_keluar, created_at) VALUES (13, 4, 1000, 400, '13 December 2023, 09:51:57');


--
-- TOC entry 4815 (class 0 OID 16404)
-- Dependencies: 216
-- Data for Name: tb_products; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.tb_products (id, nama_product, harga, photo, jumlah) VALUES (2, 'Sari Roti - Coklat', 7000, 'photo-1702008990469-602509624.png', 0);
INSERT INTO public.tb_products (id, nama_product, harga, photo, jumlah) VALUES (6, 'parfum', 30000, 'photo-1702226515810-559023689.jpeg', 0);
INSERT INTO public.tb_products (id, nama_product, harga, photo, jumlah) VALUES (5, 'Biscuit', 10000, 'photo-1702226110776-352537685.png', 0);
INSERT INTO public.tb_products (id, nama_product, harga, photo, jumlah) VALUES (3, 'sepatu', 15000, 'photo-1702015895847-951144204.png', 100);
INSERT INTO public.tb_products (id, nama_product, harga, photo, jumlah) VALUES (4, 'jaket', 10000, 'photo-1702019900972-887776248.png', 550);
INSERT INTO public.tb_products (id, nama_product, harga, photo, jumlah) VALUES (7, 'tas sekolah', 50000, 'photo-1702226931178-244985452.jpeg', 350);


--
-- TOC entry 4817 (class 0 OID 16416)
-- Dependencies: 218
-- Data for Name: tb_transaksi; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.tb_transaksi (id, invoice, id_users, created_at) VALUES (8, 'INV/20231113/MPL/3437038590', 3, '13 December 2023, 09:51:57');
INSERT INTO public.tb_transaksi (id, invoice, id_users, created_at) VALUES (9, 'INV/20231113/MPL/3437098434', 3, '13 December 2023, 09:51:57');


--
-- TOC entry 4814 (class 0 OID 16399)
-- Dependencies: 215
-- Data for Name: tb_users; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.tb_users (id, email, password, nama, no_telp, role_id) VALUES (2, 'admin@gmail.com', '$2b$10$O.bcowWq3Dg439T.o9Dkz.LT7kD8Q95dLm113LB4Btpe/0R3OvH/K', 'alex', '091233334444', 2);
INSERT INTO public.tb_users (id, email, password, nama, no_telp, role_id) VALUES (3, 'user@gmail.com', '$2b$10$lkgOQcgN4ctyGCw6YUX1PujqmhvNC7mkr5mXMrBvHkPnvKTcNVu/.', 'aldi', '081244443333', 3);
INSERT INTO public.tb_users (id, email, password, nama, no_telp, role_id) VALUES (1, 'super@gmail.com', '$2b$10$2SeWBoHuoeSWvYrW80YbKOvoZy96lyut2dPLLaVJQ7nLRANoLP1ra', 'Super Adm', '089877776661', 1);


--
-- TOC entry 4832 (class 0 OID 0)
-- Dependencies: 226
-- Name: tb_cart_temp_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tb_cart_temp_id_seq', 11, true);


--
-- TOC entry 4833 (class 0 OID 0)
-- Dependencies: 224
-- Name: tb_detail_transaksi_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tb_detail_transaksi_id_seq', 11, true);


--
-- TOC entry 4834 (class 0 OID 0)
-- Dependencies: 223
-- Name: tb_inventory_products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tb_inventory_products_id_seq', 13, true);


--
-- TOC entry 4835 (class 0 OID 0)
-- Dependencies: 222
-- Name: tb_products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tb_products_id_seq', 7, true);


--
-- TOC entry 4836 (class 0 OID 0)
-- Dependencies: 221
-- Name: tb_transaksi_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tb_transaksi_id_seq', 9, true);


--
-- TOC entry 4837 (class 0 OID 0)
-- Dependencies: 220
-- Name: tb_users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tb_users_id_seq', 3, true);


--
-- TOC entry 4670 (class 2606 OID 16435)
-- Name: tb_cart_temp tb_cart_temp_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_cart_temp
    ADD CONSTRAINT tb_cart_temp_pkey PRIMARY KEY (id);


--
-- TOC entry 4668 (class 2606 OID 16425)
-- Name: tb_detail_transaksi tb_detail_transaksi_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_detail_transaksi
    ADD CONSTRAINT tb_detail_transaksi_pkey PRIMARY KEY (id);


--
-- TOC entry 4664 (class 2606 OID 16415)
-- Name: tb_inventory_products tb_inventory_products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_inventory_products
    ADD CONSTRAINT tb_inventory_products_pkey PRIMARY KEY (id);


--
-- TOC entry 4662 (class 2606 OID 16410)
-- Name: tb_products tb_products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_products
    ADD CONSTRAINT tb_products_pkey PRIMARY KEY (id);


--
-- TOC entry 4666 (class 2606 OID 16420)
-- Name: tb_transaksi tb_transaksi_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_transaksi
    ADD CONSTRAINT tb_transaksi_pkey PRIMARY KEY (id);


--
-- TOC entry 4660 (class 2606 OID 16403)
-- Name: tb_users tb_users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_users
    ADD CONSTRAINT tb_users_pkey PRIMARY KEY (id);


-- Completed on 2023-12-16 14:21:54

--
-- PostgreSQL database dump complete
--

